### ISSUE TITLE
Turn into .exe

### ISSUE THREAD

**Issue by 8fn** [7zx/overload#24]
@7zx

**Comment by tjhasan** [comment]
Just to be sure, are you wanting to turn the overload.py application into a .exe file? If that's all, I can go ahead and do that. I'll create 2, one for Linux and the other for Windows. Should I just add them to the repo and create a pull request?

**Comment by 8fn** [comment]
> Just to be sure, are you wanting to turn the overload.py application into a .exe file? If that's all, I can go ahead and do that. I'll create 2, one for Linux and the other for Windows. Should I just add them to the repo and create a pull request?

Go ahead, create a pull request.

**Comment by Nexuzzzz** [comment]
just compile it yourself using PyInstaller or Py2Exe

**Comment by joao-vitor-souza** [comment]
I was thinking if this is actually necessary. I mean, if we want to obfuscate the code we can use `pyarmor`, if we need velocity we can use some Just In Time compiler package as `pypy` or `numba` (or completely transpile the code to C with `Cython`?), now if we are talking about distribution, then we'll have +15MB executables with `pyinstaller` or `pyOxidizer` since they need to include the python interpreter within the application. For me, it doesn't make sense to turn it into an .exe now. Any thoughts?
